export const content = {
  fa: {
    dir: 'rtl',
    localeName: 'فارسی',
    localeHint: 'نسخه اصلی',
    theme: {
      accent: '#8b5cf6',
      accent2: '#06b6d4',
      accent3: '#f59e0b',
      glow: 'rgba(139, 92, 246, 0.20)',
    },
    nav: {
      about: 'درباره',
      services: 'خدمات',
      works: 'نمونه‌کار',
      process: 'فرآیند',
      contact: 'تماس',
    },
    hero: {
      kicker: 'استودیو ساخت فیلم و ویدیو تبلیغاتی',
      title: 'از ایده تا اجرا، روایت برندتان را می‌سازیم.',
      text: 'از سناریو و پیش‌تولید تا فیلم‌برداری، تدوین، موشن و انتشار؛ همه چیز با تیمی مجرب و حرفه‌ای انجام می‌شود تا خروجی، دقیق و اثرگذار باشد.',
      slogan: 'از ایده تا اجرا همراه شماییم با کادری مجرب و حرفه ای تا شمارا به درستی روایت کنیم',
      primary: 'دیدن نمونه‌کارها',
      secondary: 'شروع همکاری',
      noteTitle: 'روایت مینیمال، خروجی خفن',
      noteText: 'مناسب برای کمپین تبلیغاتی، معرفی محصول، تیزر برند و ویدیوهای شبکه‌های اجتماعی.',
    },
    stats: [
      { value: '0-100', label: 'فرآیند کامل' },
      { value: '24/7', label: 'پاسخ‌گویی' },
      { value: '100%', label: 'پروژه اختصاصی' },
    ],
    services: {
      kicker: 'خدمات',
      title: 'خدماتی که همه چیز را یک‌دست می‌کند',
      subtitle: 'یک مسیر ساده و حرفه‌ای برای ساخت ویدیوهای تبلیغاتی که از ابتدا تا انتها کنترل شده و تمیز پیش می‌روند.',
      items: [
        { title: 'ایده‌پردازی و سناریو', text: 'از پیام برند تا ساختار روایت، همه‌چیز با متن و ایده‌ای دقیق شروع می‌شود.' },
        { title: 'فیلم‌برداری و تولید', text: 'تصویربرداری، نور، صدا و اجرای صحنه با استانداردی شیک و حرفه‌ای.' },
        { title: 'تدوین و نسخه نهایی', text: 'ادیت، رنگ، موشن و خروجی‌های تبلیغاتی آماده انتشار در همه پلتفرم‌ها.' },
      ],
    },
    projects: {
      kicker: 'نمونه‌کار',
      title: 'خروجی‌هایی که حس برند را بالا می‌برند',
      subtitle: 'چند نمونه جهت نمایش نوع روایت، ریتم بصری و کیفیت خروجی نهایی.',
      items: [
        {
          tag: 'Brand Film',
          title: 'فیلم معرفی برند',
          text: 'روایت یکپارچه برای معرفی برند با زبان تصویری تمیز، لوکس و تاثیرگذار.',
          points: ['اسکریپت و استوری‌بورد', 'فیلم‌برداری و نورپردازی', 'تدوین و نسخه تبلیغاتی'],
        },
        {
          tag: 'Product Ad',
          title: 'ویدیو تبلیغ محصول',
          text: 'نمایش محصول با قاب‌بندی حرفه‌ای، ریتم مناسب و تمرکز روی پیام فروش.',
          points: ['سناریوی کوتاه', 'تصویرسازی دقیق', 'نسخه مناسب شبکه‌های اجتماعی'],
        },
      ],
    },
    timeline: {
      kicker: 'فرآیند',
      title: 'از ایده تا انتشار در سه قدم',
      subtitle: 'فرآیندی روشن، سریع و قابل‌اعتماد برای تحویل خروجی نهایی.',
      items: [
        { time: '01', text: 'شناخت برند، هدف و لحن مناسب برای روایت.' },
        { time: '02', text: 'تولید، فیلم‌برداری و تدوین با هماهنگی کامل.' },
        { time: '03', text: 'تحویل نسخه‌های نهایی برای تبلیغات، سایت و شبکه‌های اجتماعی.' },
      ],
    },
    contact: {
      kicker: 'تماس',
      title: 'برای شروع پروژه آماده‌ایم',
      subtitle: 'برای سفارش ویدیو تبلیغاتی، معرفی برند یا تیزر کمپین، از همین‌جا در تماس باشید.',
      email: 'hello@metasho.com',
      phone: '+98 21 0000 0000',
      location: 'تهران | پروژه‌های داخلی و بین‌المللی',
    },
    footer: 'Metasho — ساخت فیلم و ویدیو تبلیغاتی',
  },
  en: {
    dir: 'ltr',
    localeName: 'English',
    localeHint: 'Primary',
    theme: {
      accent: '#7c3aed',
      accent2: '#0ea5e9',
      accent3: '#f59e0b',
      glow: 'rgba(124, 58, 237, 0.20)',
    },
    nav: { about: 'About', services: 'Services', works: 'Works', process: 'Process', contact: 'Contact' },
    hero: {
      kicker: 'Advertising film & video studio',
      title: 'From idea to execution, we shape your brand story.',
      text: 'From script and pre-production to filming, editing, motion, and delivery — everything is handled by an experienced team with a clean, premium finish.',
      slogan: 'From idea to execution, with an experienced and professional team telling your story the right way.',
      primary: 'View work',
      secondary: 'Start a project',
      noteTitle: 'Minimal, polished, memorable',
      noteText: 'Built for brand films, product ads, launch campaigns, and social content.',
    },
    stats: [
      { value: '0-100', label: 'Full process' },
      { value: '24/7', label: 'Response' },
      { value: '100%', label: 'Custom work' },
    ],
    services: {
      kicker: 'Services',
      title: 'A complete, streamlined production flow',
      subtitle: 'A simple process for premium ad videos that stay controlled from first idea to final delivery.',
      items: [
        { title: 'Concept & script', text: 'Clear messaging, strong storytelling, and a plan that matches the brand goal.' },
        { title: 'Filming & production', text: 'Camera, light, sound, and scene direction handled with a clean professional standard.' },
        { title: 'Editing & delivery', text: 'Color, motion, and final exports ready for ads, web, and social platforms.' },
      ],
    },
    projects: {
      kicker: 'Works',
      title: 'Output that elevates the brand feeling',
      subtitle: 'A few examples of visual rhythm, storytelling, and final delivery quality.',
      items: [
        { tag: 'Brand Film', title: 'Brand introduction film', text: 'A unified visual story for premium brand presentation.', points: ['Script & storyboard', 'Filming & lighting', 'Editing & ad versions'] },
        { tag: 'Product Ad', title: 'Product promotion video', text: 'Focused on the product, the message, and a strong sales rhythm.', points: ['Short-form concept', 'Precise visuals', 'Social-ready versions'] },
      ],
    },
    timeline: {
      kicker: 'Process',
      title: 'Idea to publish in three steps',
      subtitle: 'A clear workflow that keeps production fast and reliable.',
      items: [
        { time: '01', text: 'Understand the brand, the goal, and the right tone.' },
        { time: '02', text: 'Produce, film, and edit with full coordination.' },
        { time: '03', text: 'Deliver final versions for ads, web, and social.' },
      ],
    },
    contact: {
      kicker: 'Contact',
      title: 'Ready to begin',
      subtitle: 'For advertising films, brand videos, or campaign teasers, reach out here.',
      email: 'hello@metasho.com',
      phone: '+98 21 0000 0000',
      location: 'Tehran | Local & international projects',
    },
    footer: 'Metasho — Advertising film & video studio',
  },
  ar: {
    dir: 'rtl',
    localeName: 'العربية',
    localeHint: 'النسخة الثانوية',
    theme: {
      accent: '#ec4899',
      accent2: '#14b8a6',
      accent3: '#f59e0b',
      glow: 'rgba(236, 72, 153, 0.18)',
    },
    nav: { about: 'نبذة', services: 'الخدمات', works: 'الأعمال', process: 'العملية', contact: 'التواصل' },
    hero: {
      kicker: 'استوديو أفلام وفيديو إعلاني',
      title: 'من الفكرة إلى التنفيذ، نصنع قصة علامتك.',
      text: 'من كتابة السيناريو والإنتاج المسبق إلى التصوير والمونتاج والموشن والتسليم؛ كل شيء يتم عبر فريق محترف وبلمسة أنيقة.',
      slogan: 'من الفكرة إلى التنفيذ، مع فريق محترف يروي قصتك بالطريقة الصحيحة.',
      primary: 'استعراض الأعمال',
      secondary: 'بدء مشروع',
      noteTitle: 'بسيط، راقٍ، ولافت',
      noteText: 'مناسب لأفلام العلامة، إعلانات المنتجات، حملات الإطلاق، ومحتوى السوشيال.',
    },
    stats: [
      { value: '0-100', label: 'عملية كاملة' },
      { value: '24/7', label: 'استجابة' },
      { value: '100%', label: 'عمل مخصص' },
    ],
    services: {
      kicker: 'الخدمات',
      title: 'مسار إنتاج كامل وواضح',
      subtitle: 'عملية بسيطة لإعلانات فيديو فاخرة تبقى مضبوطة من أول فكرة إلى آخر تسليم.',
      items: [
        { title: 'الفكرة والسيناريو', text: 'رسالة واضحة وحكاية قوية وخطة تناسب هدف العلامة.' },
        { title: 'التصوير والإنتاج', text: 'كاميرا وإضاءة وصوت وإخراج بمستوى احترافي ونظيف.' },
        { title: 'المونتاج والتسليم', text: 'ألوان وموشن وتصديرات جاهزة للإعلانات والويب والسوشيال.' },
      ],
    },
    projects: {
      kicker: 'الأعمال',
      title: 'مخرجات ترفع إحساس العلامة',
      subtitle: 'بعض الأمثلة على الإيقاع البصري، والسرد، وجودة التسليم النهائي.',
      items: [
        { tag: 'Brand Film', title: 'فيلم تعريف بالعلامة', text: 'قصة بصرية موحّدة لتقديم العلامة بشكل فاخر.', points: ['سيناريو ولوح بصري', 'تصوير وإضاءة', 'مونتاج ونسخ إعلانية'] },
        { tag: 'Product Ad', title: 'فيديو ترويجي للمنتج', text: 'تركيز على المنتج والرسالة وإيقاع البيع.', points: ['فكرة قصيرة', 'مشاهد دقيقة', 'نسخ جاهزة للسوشيال'] },
      ],
    },
    timeline: {
      kicker: 'العملية',
      title: 'من الفكرة إلى النشر بثلاث خطوات',
      subtitle: 'منهج واضح يحافظ على السرعة والاعتمادية في الإنتاج.',
      items: [
        { time: '01', text: 'فهم العلامة والهدف والنبرة المناسبة.' },
        { time: '02', text: 'تنفيذ التصوير والمونتاج بتنسيق كامل.' },
        { time: '03', text: 'تسليم النسخ النهائية للإعلانات والويب والسوشيال.' },
      ],
    },
    contact: {
      kicker: 'التواصل',
      title: 'جاهزون للبدء',
      subtitle: 'لأفلام الإعلان أو فيديوهات العلامة أو تهيئات الحملات، تواصل معنا هنا.',
      email: 'hello@metasho.com',
      phone: '+98 21 0000 0000',
      location: 'طهران | مشاريع محلية ودولية',
    },
    footer: 'Metasho — استوديو أفلام وفيديو إعلاني',
  },
};
